import { DefenseBase, FlightData, SatelliteData, ThermalAnomaly, ThreatAlert, VesselData } from "@/types/intelligence";

export const BANGLADESH_DEFENSE_BASES: DefenseBase[] = [
  // BANGLADESH AIR FORCE & NAVY
  {
    id: "baf-kurmitola",
    name: "BAF Base Bangabandhu (Kurmitola)",
    branch: "AIR_FORCE",
    latitude: 23.8433,
    longitude: 90.3978,
    code: "VGHS / BAF-KRM",
    runwayLengthMeters: 3200,
    radarRangeKm: 350,
    missileDefenseRangeKm: 120,
    assets: ["MiG-29 Multi-Role Fighters", "F-7BGI Interceptors", "YLC-6 Early Warning Radar", "FM-90 SAM Air Defense"],
    status: "OPERATIONAL",
  },
  {
    id: "baf-zahurul",
    name: "BAF Base Zahurul Haque (Chittagong)",
    branch: "AIR_FORCE",
    latitude: 22.2500,
    longitude: 91.8133,
    code: "VGEG / BAF-ZHR",
    runwayLengthMeters: 2900,
    radarRangeKm: 400,
    missileDefenseRangeKm: 150,
    assets: ["F-7BGI Air Superiority Interceptors", "Kronos Grand 3D AESA Radar", "HQ-7 / FM-90 SAM", "Bell 212 / Mi-171Sh"],
    status: "HIGH_ALERT",
  },
  {
    id: "baf-matiur",
    name: "BAF Base Matiur Rahman (Jashore)",
    branch: "AIR_FORCE",
    latitude: 23.1838,
    longitude: 89.1608,
    code: "VGJR / BAF-MTR",
    runwayLengthMeters: 2750,
    radarRangeKm: 320,
    missileDefenseRangeKm: 80,
    assets: ["K-8W Jet Attack Trainers", "PT-6", "3D Tactical Air Defense Radar"],
    status: "OPERATIONAL",
  },
  {
    id: "baf-cox",
    name: "BAF Base Sheikh Hasina (Cox's Bazar)",
    branch: "AIR_FORCE",
    latitude: 21.4520,
    longitude: 91.9639,
    code: "VGCB / BAF-CXB",
    runwayLengthMeters: 3050,
    radarRangeKm: 380,
    missileDefenseRangeKm: 100,
    assets: ["Maritime Patrol Interceptors", "Bayraktar TB2 UCAV Drones", "Early Warning Radar", "Coastal SAM"],
    status: "HIGH_ALERT",
  },
  {
    id: "baf-tangail",
    name: "BAF Base Paharkanchanpur (Tangail Air Defense Hub)",
    branch: "AIR_FORCE",
    latitude: 24.3800,
    longitude: 90.0200,
    code: "BAF-PKP",
    runwayLengthMeters: 2400,
    radarRangeKm: 420,
    missileDefenseRangeKm: 140,
    assets: ["Air Defense Sector Operations Center", "Long Range 3D Radar", "SAM Deployment Network"],
    status: "OPERATIONAL",
  },
  {
    id: "bns-isa-khan",
    name: "BNS Isa Khan (Chittagong Naval Fleet HQ)",
    branch: "NAVY",
    latitude: 22.2894,
    longitude: 91.7997,
    code: "BNS-ISK",
    radarRangeKm: 320,
    missileDefenseRangeKm: 90,
    assets: ["Guided Missile Frigates (BNS Bangabandhu, BNS Somudra Joy)", "Type 056 Corvettes", "C-802A Anti-Ship Coastal Batteries"],
    status: "OPERATIONAL",
  },
  {
    id: "bns-sheikh-hasina-sub",
    name: "BNS Sheikh Hasina Submarine Base (Pekua)",
    branch: "NAVY",
    latitude: 21.7820,
    longitude: 91.9180,
    code: "BNS-SUB-PKU",
    radarRangeKm: 280,
    missileDefenseRangeKm: 85,
    assets: ["Type 035G Ming-Class Submarines (BNS Nabajatra, BNS Joyjatra)", "Submarine Pens", "Sonar Array Network"],
    status: "HIGH_ALERT",
  },
  {
    id: "bns-titumir",
    name: "BNS Titumir (Mongla Naval Command)",
    branch: "NAVY",
    latitude: 22.4833,
    longitude: 89.5833,
    code: "BNS-TTM",
    radarRangeKm: 220,
    missileDefenseRangeKm: 50,
    assets: ["Offshore Patrol Vessels", "Fast Attack Craft (Missile)", "Sundarbans Coastal Radar Network"],
    status: "OPERATIONAL",
  },

  // REGIONAL STRATEGIC BASES (INDIA & MYANMAR)
  {
    id: "iaf-hasimara",
    name: "IAF Hasimara Air Force Station (Rafale Base)",
    branch: "AIR_FORCE",
    latitude: 26.7025,
    longitude: 89.3700,
    code: "IAF-HSM / 101 SQN",
    runwayLengthMeters: 2740,
    radarRangeKm: 450,
    missileDefenseRangeKm: 250,
    assets: ["Dassault Rafale Multi-Role Fighters (101 Sqn Falcons)", "S-400 Triumf SAM Air Defense Unit", "Rohini 3D AESA Radar"],
    status: "HIGH_ALERT",
  },
  {
    id: "iaf-kalaikunda",
    name: "IAF Kalaikunda Air Force Station",
    branch: "AIR_FORCE",
    latitude: 22.3400,
    longitude: 87.2100,
    code: "IAF-KKD",
    runwayLengthMeters: 3000,
    radarRangeKm: 400,
    missileDefenseRangeKm: 180,
    assets: ["Sukhoi Su-30MKI Air Superiority Fighters", "Spyder-MR Air Defense SAM", "Arudhra Medium Power Radar"],
    status: "OPERATIONAL",
  },
  {
    id: "iaf-tezpur",
    name: "IAF Tezpur Air Force Station",
    branch: "AIR_FORCE",
    latitude: 26.7100,
    longitude: 92.7800,
    code: "IAF-TZP",
    runwayLengthMeters: 2750,
    radarRangeKm: 420,
    missileDefenseRangeKm: 160,
    assets: ["Sukhoi Su-30MKI", "Akash Air Defense SAM System", "Tactical 3D Radars"],
    status: "OPERATIONAL",
  },
  {
    id: "iaf-bagdogra",
    name: "IAF Bagdogra Air Force Station (Siliguri Corridor)",
    branch: "AIR_FORCE",
    latitude: 26.6800,
    longitude: 88.3300,
    code: "IAF-BGD",
    runwayLengthMeters: 2750,
    radarRangeKm: 350,
    missileDefenseRangeKm: 100,
    assets: ["Mi-17V5 Combat Transport", "An-32", "ELINT Signal Intercept Post"],
    status: "OPERATIONAL",
  },
  {
    id: "maf-sittwe",
    name: "Myanmar Air Force Station Sittwe (Akyab)",
    branch: "AIR_FORCE",
    latitude: 20.1300,
    longitude: 92.8700,
    code: "MAF-STW",
    runwayLengthMeters: 2130,
    radarRangeKm: 300,
    missileDefenseRangeKm: 70,
    assets: ["FTC-2000G Light Combat Aircraft", "K-8 Karakorum Attack Jets", "Coastal Air Defense Artillery"],
    status: "HIGH_ALERT",
  },
  {
    id: "in-andaman-portblair",
    name: "INS Utkrosh / Port Blair (Andaman Naval Air Station)",
    branch: "NAVY",
    latitude: 11.6400,
    longitude: 92.7300,
    code: "IN-UTK",
    runwayLengthMeters: 3300,
    radarRangeKm: 480,
    missileDefenseRangeKm: 200,
    assets: ["Boeing P-8I Neptune Maritime Reconnaissance", "Dornier 228 Maritime Patrol", "Barak-8 Long Range SAM"],
    status: "OPERATIONAL",
  }
];

export const INITIAL_FLIGHTS: FlightData[] = [
  // BAF TACTICAL PATROL
  {
    icao24: "7003a1",
    callsign: "BAF-701",
    origin_country: "Bangladesh",
    latitude: 23.6200,
    longitude: 90.7500,
    baro_altitude: 9200,
    velocity: 270,
    true_track: 145,
    vertical_rate: 1.8,
    squawk: "7700",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  {
    icao24: "7003a2",
    callsign: "TB2-ALPHA",
    origin_country: "Bangladesh",
    latitude: 21.6500,
    longitude: 91.8500,
    baro_altitude: 6800,
    velocity: 65,
    true_track: 210,
    vertical_rate: 0,
    squawk: "2410",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  // IAF STRATEGIC RADAR & PATROL TRACKS
  {
    icao24: "iaf091",
    callsign: "RAFA-101",
    origin_country: "India",
    latitude: 26.6500,
    longitude: 89.2000,
    baro_altitude: 12500,
    velocity: 320,
    true_track: 115,
    vertical_rate: 3.2,
    squawk: "5211",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "ELEVATED",
    lastContact: Date.now(),
  },
  {
    icao24: "iaf092",
    callsign: "NETRA-01",
    origin_country: "India",
    latitude: 25.1000,
    longitude: 88.4000,
    baro_altitude: 10800,
    velocity: 215,
    true_track: 350,
    vertical_rate: 0,
    squawk: "4401",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "HIGH",
    lastContact: Date.now(),
  },
  {
    icao24: "iaf093",
    callsign: "SU30-FLANKER",
    origin_country: "India",
    latitude: 22.8000,
    longitude: 87.6000,
    baro_altitude: 11200,
    velocity: 290,
    true_track: 85,
    vertical_rate: 0,
    squawk: "6120",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "ELEVATED",
    lastContact: Date.now(),
  },
  {
    icao24: "in094",
    callsign: "P8I-NEPTUNE",
    origin_country: "India",
    latitude: 19.8000,
    longitude: 89.2000,
    baro_altitude: 7200,
    velocity: 220,
    true_track: 70,
    vertical_rate: -0.5,
    squawk: "3310",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "HIGH",
    lastContact: Date.now(),
  },
  // UNIDENTIFIED STEALTH / BORDER PROXIMITY TRACK
  {
    icao24: "unk991",
    callsign: "TGT-GHOST",
    origin_country: "Unknown",
    latitude: 20.9500,
    longitude: 92.4500,
    baro_altitude: 4200,
    velocity: 330,
    true_track: 330,
    vertical_rate: 6.0,
    squawk: "0000",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "HIGH",
    lastContact: Date.now(),
  },
  // COMMERCIAL FLIGHTS (Biman, IndiGo, Singapore, Emirates)
  {
    icao24: "7001b4",
    callsign: "BBC-048",
    origin_country: "Bangladesh",
    latitude: 23.9500,
    longitude: 90.3500,
    baro_altitude: 4800,
    velocity: 180,
    true_track: 210,
    vertical_rate: -3.5,
    squawk: "2412",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  {
    icao24: "7008cf",
    callsign: "BSV-312",
    origin_country: "Bangladesh",
    latitude: 22.3500,
    longitude: 91.7500,
    baro_altitude: 9800,
    velocity: 210,
    true_track: 180,
    vertical_rate: 0,
    squawk: "1000",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  {
    icao24: "8002df",
    callsign: "AIC-782",
    origin_country: "India",
    latitude: 24.8500,
    longitude: 89.9200,
    baro_altitude: 10600,
    velocity: 235,
    true_track: 110,
    vertical_rate: 0.2,
    squawk: "3312",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  {
    icao24: "7009aa",
    callsign: "S2-AMG",
    origin_country: "Bangladesh",
    latitude: 24.3200,
    longitude: 88.6000,
    baro_altitude: 6100,
    velocity: 180,
    true_track: 120,
    vertical_rate: 1.0,
    squawk: "4421",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  }
];

export const INITIAL_VESSELS: VesselData[] = [
  {
    mmsi: "405000101",
    name: "BNS BANGABANDHU (F-25)",
    type: "NAVAL",
    flag: "BD",
    latitude: 21.3200,
    longitude: 91.4500,
    speed: 18.5,
    heading: 195,
    destination: "BAY OF BENGAL PATROL ZONE A",
    status: "PATROL",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "405000202",
    name: "BNS BIJOY (F-35)",
    type: "NAVAL",
    flag: "BD",
    latitude: 20.7500,
    longitude: 91.8800,
    speed: 16.0,
    heading: 140,
    destination: "ST. MARTIN EXCLUSIVE ECONOMIC ZONE",
    status: "PATROL",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "405000303",
    name: "BNS NABAJATRA (S-161)",
    type: "SUBMARINE",
    flag: "BD",
    latitude: 20.2500,
    longitude: 90.9500,
    speed: 11.2,
    heading: 220,
    destination: "DEEP MARITIME SECTOR CHARLIE",
    status: "PATROL",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "419000501",
    name: "INS SAHYADRI (F-49)",
    type: "NAVAL",
    flag: "IN",
    latitude: 19.4500,
    longitude: 89.1500,
    speed: 19.0,
    heading: 65,
    destination: "EASTERN NAVAL FLEET EXERCISE",
    status: "INTERCEPT",
    threatLevel: "SUSPICIOUS",
  },
  {
    mmsi: "563000889",
    name: "MV OCEAN GLORY",
    type: "CARGO",
    flag: "SG",
    latitude: 21.6500,
    longitude: 91.6000,
    speed: 12.8,
    heading: 350,
    destination: "CHITTAGONG PORT ANCHORAGE",
    status: "UNDERWAY",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "413998120",
    name: "FV YUAN YANG 802",
    type: "FISHING",
    flag: "CN",
    latitude: 20.1200,
    longitude: 91.2000,
    speed: 6.2,
    heading: 280,
    destination: "INTERNATIONAL WATERS",
    status: "UNDERWAY",
    threatLevel: "SUSPICIOUS",
  }
];

export const INITIAL_SATELLITES: SatelliteData[] = [
  {
    id: "bs-1",
    name: "BANGABANDHU-1 (BD-SAT-1)",
    noradId: 43464,
    type: "COMMUNICATION",
    operator: "Bangladesh (BSCL)",
    latitude: 0.0,
    longitude: 119.1,
    altitude: 35786,
    velocity: 3.07,
    footprintRadiusKm: 3500,
    orbitPath: [[119.1, 0.0]],
  },
  {
    id: "cartosat-3",
    name: "CARTOSAT-3 (0.25m High-Res Recon)",
    noradId: 44804,
    type: "OPTICAL_RECON",
    operator: "India (ISRO / MoD)",
    latitude: 23.4,
    longitude: 90.1,
    altitude: 505,
    velocity: 7.6,
    footprintRadiusKm: 850,
    orbitPath: [[89.0, 26.0], [90.1, 23.4], [91.2, 20.8]],
  },
  {
    id: "risat-2br1",
    name: "RISAT-2BR1 (All-Weather SAR Radar)",
    noradId: 44857,
    type: "SAR_RADAR",
    operator: "India (ISRO / NTRO)",
    latitude: 21.8,
    longitude: 92.5,
    altitude: 576,
    velocity: 7.58,
    footprintRadiusKm: 920,
    orbitPath: [[91.0, 24.5], [92.5, 21.8], [94.0, 19.1]],
  },
  {
    id: "emisat",
    name: "EMISAT (Electronic Intelligence ELINT)",
    noradId: 44078,
    type: "OPTICAL_RECON",
    operator: "India (DRDO)",
    latitude: 24.2,
    longitude: 88.8,
    altitude: 748,
    velocity: 7.47,
    footprintRadiusKm: 1100,
    orbitPath: [[87.5, 27.0], [88.8, 24.2], [90.1, 21.4]],
  }
];

export const INITIAL_THERMAL_ANOMALIES: ThermalAnomaly[] = [
  {
    id: "thm-01",
    latitude: 21.2500,
    longitude: 92.3500,
    brightness: 342.5,
    confidence: 94,
    satellite: "VIIRS",
    detectionTime: "LIVE (12 min ago)",
    areaDescription: "Myanmar Frontier Sector 4 (Rakhine Border)",
    riskType: "BORDER_ACTIVITY",
  },
  {
    id: "thm-02",
    latitude: 24.8500,
    longitude: 91.9500,
    brightness: 318.2,
    confidence: 88,
    satellite: "MODIS",
    detectionTime: "LIVE (28 min ago)",
    areaDescription: "Meghalaya Highland Corridor",
    riskType: "FOREST_FIRE",
  },
  {
    id: "thm-03",
    latitude: 22.1500,
    longitude: 89.4500,
    brightness: 329.0,
    confidence: 81,
    satellite: "VIIRS",
    detectionTime: "LIVE (45 min ago)",
    areaDescription: "Sundarbans Coastal Sector",
    riskType: "INDUSTRIAL",
  }
];

export const INITIAL_THREAT_ALERTS: ThreatAlert[] = [
  {
    id: "alt-01",
    timestamp: "JUST NOW",
    level: "DEFCON_2",
    severity: "CRITICAL",
    title: "UNKNOWN FAST MOVER AIR CONTACT (330 KTS)",
    description: "Unidentified radar contact detected approaching South-East ADIZ boundary at Mach 0.5. Transponder Squawk 0000 non-responsive.",
    sector: "SE-ADIZ (COX'S BAZAR / NAF RIVER FRONTIER)",
    coordinates: [92.4500, 20.9500],
  },
  {
    id: "alt-02",
    timestamp: "4m ago",
    level: "DEFCON_3",
    severity: "HIGH",
    title: "IAF NETRA AEW&CS AIRBORNE ORBIT DETECTED",
    description: "Indian Air Force Early Warning Aircraft active in West Bengal sector with 450km radar footprint scanning Northern Bangladesh.",
    sector: "NW SECTOR (SILIGURI / RANGPUR CORRIDOR)",
    coordinates: [88.4000, 25.1000],
  },
  {
    id: "alt-03",
    timestamp: "18m ago",
    level: "DEFCON_4",
    severity: "MEDIUM",
    title: "SAR SATELLITE OVERPASS INCOMING",
    description: "RISAT-2BR1 Synthetic Aperture Radar satellite entering Bay of Bengal observation footprint at 576km orbital altitude.",
    sector: "MARITIME EEZ SECTOR CHARLIE",
    coordinates: [91.8000, 21.2000],
  }
];
