import { DefenseBase, FlightData, SatelliteData, ThermalAnomaly, ThreatAlert, VesselData } from "@/types/intelligence";

export const BANGLADESH_DEFENSE_BASES: DefenseBase[] = [
  {
    id: "baf-kurmitola",
    name: "BAF Base Bangabandhu (Kurmitola)",
    branch: "AIR_FORCE",
    latitude: 23.8433,
    longitude: 90.3978,
    code: "VGHS / BAF-KRM",
    runwayLengthMeters: 3200,
    radarRangeKm: 350,
    missileDefenseRangeKm: 120,
    assets: ["MiG-29", "F-7BGI", "Air Defense Early Warning Radar YLC-6", "FM-90 SAM"],
    status: "OPERATIONAL",
  },
  {
    id: "baf-zahurul",
    name: "BAF Base Zahurul Haque (Chittagong)",
    branch: "AIR_FORCE",
    latitude: 22.2500,
    longitude: 91.8133,
    code: "VGEG / BAF-ZHR",
    runwayLengthMeters: 2900,
    radarRangeKm: 400,
    missileDefenseRangeKm: 150,
    assets: ["F-7BGI Multi-role Interceptors", "Bell 212", "Kronos Grand 3D AESA Radar", "HQ-7 / FM-90"],
    status: "HIGH_ALERT",
  },
  {
    id: "baf-matiur",
    name: "BAF Base Matiur Rahman (Jashore)",
    branch: "AIR_FORCE",
    latitude: 23.1838,
    longitude: 89.1608,
    code: "VGJR / BAF-MTR",
    runwayLengthMeters: 2750,
    radarRangeKm: 320,
    missileDefenseRangeKm: 80,
    assets: ["K-8W Jet Trainers", "PT-6", "Air Defense Radar 3D"],
    status: "OPERATIONAL",
  },
  {
    id: "baf-cox",
    name: "BAF Base Sheikh Hasina (Cox's Bazar)",
    branch: "AIR_FORCE",
    latitude: 21.4520,
    longitude: 91.9639,
    code: "VGCB / BAF-CXB",
    runwayLengthMeters: 3050,
    radarRangeKm: 380,
    missileDefenseRangeKm: 100,
    assets: ["Maritime Patrol Interceptors", "Early Warning Radar", "Coastal Defense SAM"],
    status: "HIGH_ALERT",
  },
  {
    id: "bns-isa-khan",
    name: "BNS Isa Khan (Chittagong Naval HQ)",
    branch: "NAVY",
    latitude: 22.2894,
    longitude: 91.7997,
    code: "BNS-ISK",
    radarRangeKm: 300,
    missileDefenseRangeKm: 90,
    assets: ["Guided Missile Frigates (BNS Bangabandhu)", "Corvettes", "C-802A Anti-Ship Batteries"],
    status: "OPERATIONAL",
  },
  {
    id: "bns-sheikh-hasina-sub",
    name: "BNS Sheikh Hasina Submarine Base (Pekua)",
    branch: "NAVY",
    latitude: 21.7820,
    longitude: 91.9180,
    code: "BNS-SUB-PKU",
    radarRangeKm: 250,
    missileDefenseRangeKm: 75,
    assets: ["Type 035G Submarines (BNS Nabajatra, BNS Joyjatra)", "Submarine Berthing", "Acoustic Sensors"],
    status: "HIGH_ALERT",
  },
  {
    id: "bns-titumir",
    name: "BNS Titumir (Mongla Base)",
    branch: "NAVY",
    latitude: 22.4833,
    longitude: 89.5833,
    code: "BNS-TTM",
    radarRangeKm: 200,
    assets: ["Large Patrol Craft", "Offshore Fast Attack Boats", "Coastal Radars"],
    status: "OPERATIONAL",
  }
];

export const INITIAL_FLIGHTS: FlightData[] = [
  {
    icao24: "7003a1",
    callsign: "BAF-701",
    origin_country: "Bangladesh",
    latitude: 23.4200,
    longitude: 90.8500,
    baro_altitude: 8500,
    velocity: 240,
    true_track: 135,
    vertical_rate: 2.1,
    squawk: "7700",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "ELEVATED",
    lastContact: Date.now(),
  },
  {
    icao24: "7001b4",
    callsign: "BBC-048",
    origin_country: "Bangladesh",
    latitude: 23.9500,
    longitude: 90.3500,
    baro_altitude: 4200,
    velocity: 160,
    true_track: 210,
    vertical_rate: -4.5,
    squawk: "2412",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  {
    icao24: "7008cf",
    callsign: "VGO-312",
    origin_country: "Bangladesh",
    latitude: 22.3500,
    longitude: 91.7500,
    baro_altitude: 9800,
    velocity: 210,
    true_track: 180,
    vertical_rate: 0,
    squawk: "1000",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  {
    icao24: "8002df",
    callsign: "AIC-782",
    origin_country: "India",
    latitude: 24.8500,
    longitude: 89.9200,
    baro_altitude: 10600,
    velocity: 235,
    true_track: 110,
    vertical_rate: 0.2,
    squawk: "3312",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  },
  {
    icao24: "unk991",
    callsign: "TGT-GHOST",
    origin_country: "Unknown",
    latitude: 20.9500,
    longitude: 92.4500,
    baro_altitude: 3500,
    velocity: 310,
    true_track: 330,
    vertical_rate: 5.0,
    squawk: "0000",
    on_ground: false,
    category: "MILITARY",
    threatLevel: "HIGH",
    lastContact: Date.now(),
  },
  {
    icao24: "7009aa",
    callsign: "S2-AMG",
    origin_country: "Bangladesh",
    latitude: 24.3200,
    longitude: 88.6000,
    baro_altitude: 6100,
    velocity: 180,
    true_track: 120,
    vertical_rate: 1.0,
    squawk: "4421",
    on_ground: false,
    category: "COMMERCIAL",
    threatLevel: "NORMAL",
    lastContact: Date.now(),
  }
];

export const INITIAL_VESSELS: VesselData[] = [
  {
    mmsi: "405000101",
    name: "BNS BANGABANDHU (F-25)",
    type: "NAVAL",
    flag: "BD",
    latitude: 21.3200,
    longitude: 91.4500,
    speed: 18.5,
    heading: 195,
    destination: "BAY OF BENGAL PATROL ZONE A",
    status: "PATROL",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "405000202",
    name: "BNS BIJOY (F-35)",
    type: "NAVAL",
    flag: "BD",
    latitude: 20.7500,
    longitude: 91.8800,
    speed: 16.0,
    heading: 140,
    destination: "ST. MARTIN EXCLUSIVE ECONOMIC ZONE",
    status: "PATROL",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "405000303",
    name: "BNS NABAJATRA (S-161)",
    type: "SUBMARINE",
    flag: "BD",
    latitude: 20.2500,
    longitude: 90.9500,
    speed: 11.2,
    heading: 220,
    destination: "DEEP MARITIME SECTOR CHARLIE",
    status: "PATROL",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "563000889",
    name: "MV OCEAN GLORY",
    type: "CARGO",
    flag: "SG",
    latitude: 21.6500,
    longitude: 91.6000,
    speed: 12.8,
    heading: 350,
    destination: "CHITTAGONG PORT ANCHORAGE",
    status: "UNDERWAY",
    threatLevel: "NORMAL",
  },
  {
    mmsi: "413998120",
    name: "FV YUAN YANG 802",
    type: "FISHING",
    flag: "UNKNOWN",
    latitude: 20.1200,
    longitude: 92.1500,
    speed: 8.4,
    heading: 290,
    destination: "UNKNOWN / EEZ PERIMETER",
    status: "INTERCEPT",
    threatLevel: "SUSPICIOUS",
  },
  {
    mmsi: "636019230",
    name: "MT BENGAL STAR",
    type: "TANKER",
    flag: "BD",
    latitude: 21.1500,
    longitude: 89.8000,
    speed: 13.5,
    heading: 15,
    destination: "MONGLA PORT PETROLEUM JETTY",
    status: "UNDERWAY",
    threatLevel: "NORMAL",
  }
];

export const INITIAL_SATELLITES: SatelliteData[] = [
  {
    id: "sat-bs1",
    name: "Bangabandhu Satellite-1 (BD-1)",
    noradId: 43463,
    type: "COMMUNICATION",
    operator: "Bangladesh (BSCL)",
    latitude: 0.0,
    longitude: 119.1,
    altitude: 35786,
    velocity: 3.07,
    footprintRadiusKm: 4200,
    orbitPath: [
      [119.1, 0.0],
      [119.1, 0.05],
      [119.1, -0.05],
    ],
  },
  {
    id: "sat-sentinel2a",
    name: "Copernicus Sentinel-2A (Optical 10m)",
    noradId: 40697,
    type: "OPTICAL_RECON",
    operator: "ESA / Open Earth",
    latitude: 22.8,
    longitude: 90.2,
    altitude: 786,
    velocity: 7.45,
    footprintRadiusKm: 290,
    revisitFrequencyHours: 120,
    orbitPath: [
      [89.1, 15.0],
      [89.8, 19.5],
      [90.2, 22.8],
      [90.9, 26.5],
      [91.5, 30.0],
    ],
  },
  {
    id: "sat-sentinel1a",
    name: "Copernicus Sentinel-1A (SAR Radar)",
    noradId: 39634,
    type: "SAR_RADAR",
    operator: "ESA / Copernicus",
    latitude: 24.5,
    longitude: 91.8,
    altitude: 693,
    velocity: 7.51,
    footprintRadiusKm: 400,
    revisitFrequencyHours: 144,
    orbitPath: [
      [90.5, 18.0],
      [91.2, 21.5],
      [91.8, 24.5],
      [92.4, 28.0],
      [93.1, 31.5],
    ],
  },
  {
    id: "sat-iss",
    name: "International Space Station (ISS)",
    noradId: 25544,
    type: "SPACE_STATION",
    operator: "NASA / International",
    latitude: 19.4,
    longitude: 88.5,
    altitude: 418,
    velocity: 7.66,
    footprintRadiusKm: 1200,
    orbitPath: [
      [80.0, 10.0],
      [84.5, 15.2],
      [88.5, 19.4],
      [93.0, 23.1],
      [98.0, 26.0],
    ],
  },
  {
    id: "sat-recon-x9",
    name: "Sub-Meter Defense Optical Recon",
    noradId: 99412,
    type: "OPTICAL_RECON",
    operator: "Regional Surveillance Constellation",
    latitude: 21.2,
    longitude: 92.1,
    altitude: 510,
    velocity: 7.61,
    footprintRadiusKm: 150,
    revisitFrequencyHours: 24,
    orbitPath: [
      [91.0, 16.0],
      [91.6, 18.8],
      [92.1, 21.2],
      [92.8, 24.0],
    ]
  }
];

export const INITIAL_THERMAL_ANOMALIES: ThermalAnomaly[] = [
  {
    id: "th-01",
    latitude: 21.285,
    longitude: 92.215,
    brightness: 345.2,
    confidence: 88,
    satellite: "VIIRS",
    detectionTime: "15 min ago",
    areaDescription: "Rakhine Border Sector (Thermal Spike)",
    riskType: "BORDER_ACTIVITY",
  },
  {
    id: "th-02",
    latitude: 21.980,
    longitude: 92.420,
    brightness: 328.0,
    confidence: 74,
    satellite: "MODIS",
    detectionTime: "42 min ago",
    areaDescription: "Bandarban Hill Forest Perimeter",
    riskType: "FOREST_FIRE",
  },
  {
    id: "th-03",
    latitude: 22.310,
    longitude: 91.780,
    brightness: 362.4,
    confidence: 95,
    satellite: "VIIRS",
    detectionTime: "5 min ago",
    areaDescription: "Chittagong Industrial Port Zone Flare",
    riskType: "INDUSTRIAL",
  }
];

export const INITIAL_THREAT_ALERTS: ThreatAlert[] = [
  {
    id: "alt-01",
    timestamp: "06:42:15 BST",
    level: "DEFCON_3",
    severity: "HIGH",
    title: "Unidentified Transponder in Southeastern ADIZ",
    description: "Radar track TGT-GHOST at 3,500m detected moving at 310 kts approaching border sector 4.",
    sector: "SE-AIR-DEFENSE-ZONE",
    coordinates: [92.4500, 20.9500],
  },
  {
    id: "alt-02",
    timestamp: "06:35:00 BST",
    level: "DEFCON_4",
    severity: "MEDIUM",
    title: "Suspicious Maritime Contact inside St. Martin EEZ",
    description: "Vessel FV YUAN YANG 802 non-responsive to Coast Guard VHF Channel 16 interrogation.",
    sector: "BAY-OF-BENGAL-MARITIME-GRID",
    coordinates: [92.1500, 20.1200],
  },
  {
    id: "alt-03",
    timestamp: "06:10:22 BST",
    level: "DEFCON_5",
    severity: "LOW",
    title: "Copernicus Sentinel-2A Scheduled Orbit Pass",
    description: "Optical reconnaissance pass covering Chittagong & Cox's Bazar coastline commencing at 07:12 BST.",
    sector: "ORBITAL-SECTOR-ALPHA",
    coordinates: [90.2000, 22.8000],
  }
];
