import { DefenseBase } from "@/types/intelligence";

/**
 * Reference data: fixed installations.
 *
 * These are real, publicly documented facilities — coordinates come from open
 * aeronautical/OSINT sources. Radar and SAM range rings are NOMINAL published
 * envelopes for the stated equipment class, not measured or classified
 * performance, and asset lists reflect open reporting rather than a live order
 * of battle. Nothing here is a live feed: installations do not move, so this
 * file holds no simulated telemetry of any kind.
 */


export const BANGLADESH_DEFENSE_BASES: DefenseBase[] = [
  // BANGLADESH AIR FORCE & NAVY
  {
    id: "baf-kurmitola",
    name: "BAF Base Bangabandhu (Kurmitola)",
    branch: "AIR_FORCE",
    latitude: 23.8433,
    longitude: 90.3978,
    code: "VGHS / BAF-KRM",
    runwayLengthMeters: 3200,
    radarRangeKm: 350,
    missileDefenseRangeKm: 120,
    assets: ["MiG-29 Multi-Role Fighters", "F-7BGI Interceptors", "YLC-6 Early Warning Radar", "FM-90 SAM Air Defense"],
    status: "OPERATIONAL",
  },
  {
    id: "baf-zahurul",
    name: "BAF Base Zahurul Haque (Chittagong)",
    branch: "AIR_FORCE",
    latitude: 22.2500,
    longitude: 91.8133,
    code: "VGEG / BAF-ZHR",
    runwayLengthMeters: 2900,
    radarRangeKm: 400,
    missileDefenseRangeKm: 150,
    assets: ["F-7BGI Air Superiority Interceptors", "Kronos Grand 3D AESA Radar", "HQ-7 / FM-90 SAM", "Bell 212 / Mi-171Sh"],
    status: "HIGH_ALERT",
  },
  {
    id: "baf-matiur",
    name: "BAF Base Matiur Rahman (Jashore)",
    branch: "AIR_FORCE",
    latitude: 23.1838,
    longitude: 89.1608,
    code: "VGJR / BAF-MTR",
    runwayLengthMeters: 2750,
    radarRangeKm: 320,
    missileDefenseRangeKm: 80,
    assets: ["K-8W Jet Attack Trainers", "PT-6", "3D Tactical Air Defense Radar"],
    status: "OPERATIONAL",
  },
  {
    id: "baf-cox",
    name: "BAF Base Sheikh Hasina (Cox's Bazar)",
    branch: "AIR_FORCE",
    latitude: 21.4520,
    longitude: 91.9639,
    code: "VGCB / BAF-CXB",
    runwayLengthMeters: 3050,
    radarRangeKm: 380,
    missileDefenseRangeKm: 100,
    assets: ["Maritime Patrol Interceptors", "Bayraktar TB2 UCAV Drones", "Early Warning Radar", "Coastal SAM"],
    status: "HIGH_ALERT",
  },
  {
    id: "baf-tangail",
    name: "BAF Base Paharkanchanpur (Tangail Air Defense Hub)",
    branch: "AIR_FORCE",
    latitude: 24.3800,
    longitude: 90.0200,
    code: "BAF-PKP",
    runwayLengthMeters: 2400,
    radarRangeKm: 420,
    missileDefenseRangeKm: 140,
    assets: ["Air Defense Sector Operations Center", "Long Range 3D Radar", "SAM Deployment Network"],
    status: "OPERATIONAL",
  },
  {
    id: "bns-isa-khan",
    name: "BNS Isa Khan (Chittagong Naval Fleet HQ)",
    branch: "NAVY",
    latitude: 22.2894,
    longitude: 91.7997,
    code: "BNS-ISK",
    radarRangeKm: 320,
    missileDefenseRangeKm: 90,
    assets: ["Guided Missile Frigates (BNS Bangabandhu, BNS Somudra Joy)", "Type 056 Corvettes", "C-802A Anti-Ship Coastal Batteries"],
    status: "OPERATIONAL",
  },
  {
    id: "bns-sheikh-hasina-sub",
    name: "BNS Sheikh Hasina Submarine Base (Pekua)",
    branch: "NAVY",
    latitude: 21.7820,
    longitude: 91.9180,
    code: "BNS-SUB-PKU",
    radarRangeKm: 280,
    missileDefenseRangeKm: 85,
    assets: ["Type 035G Ming-Class Submarines (BNS Nabajatra, BNS Joyjatra)", "Submarine Pens", "Sonar Array Network"],
    status: "HIGH_ALERT",
  },
  {
    id: "bns-titumir",
    name: "BNS Titumir (Mongla Naval Command)",
    branch: "NAVY",
    latitude: 22.4833,
    longitude: 89.5833,
    code: "BNS-TTM",
    radarRangeKm: 220,
    missileDefenseRangeKm: 50,
    assets: ["Offshore Patrol Vessels", "Fast Attack Craft (Missile)", "Sundarbans Coastal Radar Network"],
    status: "OPERATIONAL",
  },

  // REGIONAL STRATEGIC BASES (INDIA & MYANMAR)
  {
    id: "iaf-hasimara",
    name: "IAF Hasimara Air Force Station (Rafale Base)",
    branch: "AIR_FORCE",
    latitude: 26.7025,
    longitude: 89.3700,
    code: "IAF-HSM / 101 SQN",
    runwayLengthMeters: 2740,
    radarRangeKm: 450,
    missileDefenseRangeKm: 250,
    assets: ["Dassault Rafale Multi-Role Fighters (101 Sqn Falcons)", "S-400 Triumf SAM Air Defense Unit", "Rohini 3D AESA Radar"],
    status: "HIGH_ALERT",
  },
  {
    id: "iaf-kalaikunda",
    name: "IAF Kalaikunda Air Force Station",
    branch: "AIR_FORCE",
    latitude: 22.3400,
    longitude: 87.2100,
    code: "IAF-KKD",
    runwayLengthMeters: 3000,
    radarRangeKm: 400,
    missileDefenseRangeKm: 180,
    assets: ["Sukhoi Su-30MKI Air Superiority Fighters", "Spyder-MR Air Defense SAM", "Arudhra Medium Power Radar"],
    status: "OPERATIONAL",
  },
  {
    id: "iaf-tezpur",
    name: "IAF Tezpur Air Force Station",
    branch: "AIR_FORCE",
    latitude: 26.7100,
    longitude: 92.7800,
    code: "IAF-TZP",
    runwayLengthMeters: 2750,
    radarRangeKm: 420,
    missileDefenseRangeKm: 160,
    assets: ["Sukhoi Su-30MKI", "Akash Air Defense SAM System", "Tactical 3D Radars"],
    status: "OPERATIONAL",
  },
  {
    id: "iaf-bagdogra",
    name: "IAF Bagdogra Air Force Station (Siliguri Corridor)",
    branch: "AIR_FORCE",
    latitude: 26.6800,
    longitude: 88.3300,
    code: "IAF-BGD",
    runwayLengthMeters: 2750,
    radarRangeKm: 350,
    missileDefenseRangeKm: 100,
    assets: ["Mi-17V5 Combat Transport", "An-32", "ELINT Signal Intercept Post"],
    status: "OPERATIONAL",
  },
  {
    id: "maf-sittwe",
    name: "Myanmar Air Force Station Sittwe (Akyab)",
    branch: "AIR_FORCE",
    latitude: 20.1300,
    longitude: 92.8700,
    code: "MAF-STW",
    runwayLengthMeters: 2130,
    radarRangeKm: 300,
    missileDefenseRangeKm: 70,
    assets: ["FTC-2000G Light Combat Aircraft", "K-8 Karakorum Attack Jets", "Coastal Air Defense Artillery"],
    status: "HIGH_ALERT",
  },
  {
    id: "in-andaman-portblair",
    name: "INS Utkrosh / Port Blair (Andaman Naval Air Station)",
    branch: "NAVY",
    latitude: 11.6400,
    longitude: 92.7300,
    code: "IN-UTK",
    runwayLengthMeters: 3300,
    radarRangeKm: 480,
    missileDefenseRangeKm: 200,
    assets: ["Boeing P-8I Neptune Maritime Reconnaissance", "Dornier 228 Maritime Patrol", "Barak-8 Long Range SAM"],
    status: "OPERATIONAL",
  }
];
